name: Daily Update-yml
on:
  schedule: # execute every 12 hours
    - cron: '* */24 * * *'
  push:
    branches:
      - branch_dev
jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          # cache key 包含了所有我們希望固定的資訊：OS，node 版本，以及 package-lock.json 的檔案內容，使用 hashFiles 將檔案內容轉換成字串
          key: node-modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Install Packages
        run: test -d node_modules && echo "node_modules exists" || npm ci
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      #tsc
      - name: tsc
        run: tsc
      - run: ls 
      # To Generate Files here
      - run: npm run prod
        env:  
          TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}
      - run: |
          git config --local user.email "actions@example.com"
          git config --local user.name "Github-Action"
          ls -a | grep -v "README.md\|output\|[.]$\|tv_struct.json\|movie_struct.json" | grep -v ^.git$ | xargs rm -rf
          git add --all
          git commit --amend --allow-empty -m "${{ github.workflow }}- Generated:${{ steps.date.outputs.date }}" 
          git push -f origin branch_dev:deploy
      # --allow-empty  It allow no changed commit to push preventing return error from no-changed push.
